# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ec981549d70e7d5caee6937442f5e9ed5e3e23416b4c9a0b73d1d11d2125978394828386f84182d7a800bc4e4181c20e0aa49235f8cf61e923d521b0396614

test:
  secret_key_base: f5e66e08fdb07ca4539c1cbe121b385deca33e26f952455d470df235cd7892eb55bc34bb2cf198b4bfb1c4d409cee92e24c73041329f25130a2798e2144299cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
